# Reference: https://docs.gitguardian.com/ggshield-docs/configuration
# Required, otherwise ggshield considers the file to use the deprecated v1 format
version: 2

secret:
  ignored-paths:
    - "integration-tests/tests/*"
    - "api/tests/*"
    - "dev/*"
