security:
  password_hashers:
    # Use native password hasher, which auto-selects and migrates the best
    # possible hashing algorithm (starting from Symfony 5.3 this is "bcrypt")
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  providers:
    user_provider:
      entity:
        class: App\Entity\User
        property: secretKey
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt))/
      security: false
    public:
      pattern: ^/(public|images)/
      security: false
    login:
      pattern: ^/api/login/
      lazy: true
      stateless: true
      login_throttling:
        max_attempts: 10
        interval: '60 minutes'
    main:
      lazy: true
      stateless: true
      access_token:
        token_handler: App\Security\ApiKeyAuthenticator
        token_extractors:
          - App\Security\ApiKeyExtractor
