#!/bin/sh

set -xe

initial_path="$(pwd)"

cd "$(dirname "$0")"

cdroot() {
  if ! [ -e ".git" ] && [ "$(pwd)" != "/" ]; then
    cd ..
    cdroot
  fi
}

cdroot

make dev
docker run --rm -it --name "zusam-dev" \
  -e UID="$(id -u)" -e GID="$(id -g)" \
  -v "$initial_path"/data:/zusam/data:z \
  -v "$initial_path"/public:/zusam/public:z \
  -v "$initial_path"/api:/zusam/api:z \
  -v "$initial_path"/app:/zusam/app:z \
  "zusam-dev"

cd "$initial_path"
