#!/bin/sh

set -xe

initial_path="$(pwd)"

cd "$(dirname "$0")"

cdroot() {
  if ! [ -e ".git" ] && [ "$(pwd)" != "/" ]; then
    cd ..
    cdroot
  fi
}

cdroot

make dev
docker run --rm -it -e UID="$(id -u)" -e GID="$(id -g)" -v "$initial_path":/zusam:z --name "zusam-dev" "zusam-dev"

cd "$initial_path"
