#!/bin/sh

set -xe

pgrm="$(command -v podman || command -v docker)"
initial_path="$(pwd)"

cd "$(dirname "$0")"

cdroot() {
  if ! [ -e ".git" ] && [ "$(pwd)" != "/" ]; then
    cd ..
    cdroot
  fi
}

cdroot

if [ -n "$1" ]; then
  cmd="$*"
else
  cmd="bash"
fi

make dev
"$pgrm" run --rm -it -v "$initial_path":/zusam:z --name "zusam-dev" "zusam-dev" "$cmd"

cd "$initial_path"
