const lang = {
    "fr": {
        "more_coms": "Voir les commentaires précédents",
        "there_is": "Il y a",
        "groups": "Groupes",
        "login_placeholder": "identifiant",
        "password_placeholder": "mot de passe",
		"submit": "Envoyer",
        "title_placeholder": "Titre de votre message (optionnel)",
        "text_placeholder": "Ecrivez votre message ici",
        "upload_image": "Ajouter des photos",
        "upload_video": "Ajouter des vidéos",
        "upload_music": "Ajouter des musiques",
        "add_date": "Préciser une date",
        "logout": "Se déconnecter",
        "settings": "Paramètres",
        "name": "Nom",
        "name_input": "Choisissez un nom",
        "login": "Identifiant",
        "login_input": "Choisissez un identifiant",
        "email": "Email",
        "email_input": "Renseignez votre adresse mail ici",
        "save_changes": "Sauvegardez les changements",
        "password": "Mot de passe",
        "password_input": "Entrez un nouveau mot de passe",
        "Invalid login/password": "Identifiant et/ou mot de passe invalide",
        "edit": "Editer",
        "delete": "Supprimer",
        "ask_delete_message": "Êtes-vous sûr de vouloir supprimer ce message ?",
    }
};
export default lang;
