const lang = {
    "fr": {
        "more_coms": "Voir les commentaires précédents",
        "there_is": "Il y a",
        "groups": "Groupes",
        "login_placeholder": "email",
        "password_placeholder": "mot de passe",
        "new_password_placeholder": "nouveau mot de passe",
        "confirm_password_placeholder": "confirmez le mot de passe",
        "connect": "Connexion",
		"submit": "Envoyer",
        "title_placeholder": "Titre de votre message (optionnel)",
        "text_placeholder": "Ecrivez votre message ici",
        "upload_image": "Ajouter des photos",
        "upload_video": "Ajouter des vidéos",
        "upload_music": "Ajouter des musiques",
        "add_date": "Préciser une date",
        "logout": "Se déconnecter",
        "settings": "Paramètres",
        "name": "Nom",
        "name_input": "Choisissez un nom",
        "login": "Identifiant",
        "login_input": "Choisissez un identifiant",
        "email": "Email",
        "email_input": "Renseignez votre adresse mail ici",
        "save_changes": "Sauvegardez les changements",
        "password": "Mot de passe",
        "password_input": "Entrez un nouveau mot de passe",
        "Invalid login/password": "Identifiant et/ou mot de passe invalide",
        "edit": "Editer",
        "delete": "Supprimer",
        "ask_delete_message": "Êtes-vous sûr de vouloir supprimer ce message ?",
        "account": "Compte",
        "groups": "Groupes",
        "forgot_password": "Mot de passe oublié ?",
        "password_reset_mail_sent": "Le mail de réinitialisation a bien été envoyé !",
        "User not found": "Utilisateur inexistant",
        "reset_password_title": "Réinitialisation de votre mot de passe",
        "error": "Une erreur est survenue. Veuillez réessayer.",
        "passwords_dont_match": "Les mots de passe ne sont pas identiques !",
        "invitation_link": "Lien d'invitation",
        "reset_invitation_link": "Réinitialiser le lien d'invitation",
        "invitation_welcome": "Bienvenue sur Zusam ! Veuillez vous inscrire avant de rejoindre le groupe.",
        "signup": "S'inscrire",
        "create_a_group": "Créer un groupe",
        "create_the_group": "Créer le groupe"
    }
};
export default lang;
