#!/bin/sh

set -xe

initial_path="$(pwd)"

cd "$(dirname "$0")"

. ./cdroot
. ./container_pgrm

cdroot
pgrm="$(container_pgrm)"

if [ -n "$1" ]; then
  cmd="$*"
else
  cmd="bash"
fi

if ! "$pgrm" images | grep zusam-dev >/dev/null; then
  make dev
fi
"$pgrm" run --rm -it -v "$initial_path":/zusam:z --name "zusam-dev" "zusam-dev" "$cmd"

cd "$initial_path"
