#!/bin/sh

set -xe

pgrm="$(command -v podman || command -v docker)"
initial_path="$(pwd)"

cd "$(dirname "$0")"

. ./cdroot

cdroot

make prod
"$pgrm" run --rm -it --name "zusam-test" -p 8080:8080 \
  -v "$initial_path"/data:/zusam/data:z \
  -v "$initial_path"/public:/zusam/public:z \
  -v "$initial_path"/api:/zusam/api:z \
  zusam

cd "$initial_path"
