name: Python Lint

on: [pull_request]

jobs:
  ruff:
    name: Run ruff format and lint checks
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Set up Python
        # https://github.com/actions/setup-python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.14'

      - name: Run ruff format and lint checks
        run: make lint-integ-tests
